import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar/page";
import FooterComponent from "./Components/App/footerComponent";
import SideBar from "./SideBar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const adminToken = typeof window !== "undefined" ? localStorage.getItem("adminToken") : null;

  return (

    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>

        { adminToken ? (
          <SideBar />
        ) : (
          <NavBar />
        )}
        {/* <NavBar /> */}
        <div className="flex-grow bg-slate-100 h-auto">
          {children}
        </div>
        { !adminToken && <FooterComponent />}
      </body>
    </html>

  );
}
